version: '3.9'
services:
  db:
    container_name: project-z_db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: FyONTK5IbKJP
      POSTGRES_DB: project-z
  nodejs:
    container_name: project-z_nodejs
    build: .
    ports:
      - '80:80'
    volumes:
      - .:/usr/src/app
